### PR TITLE
Create project in Android Studio with template for the mobile app

### LINKED ISSUE #14: Create template project
**Goal of the task:**
Create template project displaying "Hello world" message.

**What functionality will it affect?**
Mobile-app implementation

**Scope of the task:**
Create template project in Android Studio

**Resources and tips:**
https://developer.android.com/codelabs/build-your-first-android-app?fbclid=IwAR0EC2qLhYR7PzBzFMZMmKVoz0Z-3GFz6haLD3T0nHCE91tx_hwxpLFORqY#0

**Definition of Done:**
PR to android-mobile-app repo merged to master

### PR DESCRIPTION
**Pull request by bartoszLesniewski**
Create a basic template for mobile app. For now, it displays "Hello world" text and counts the number of clicks on "Count" button. Moreover, showing text on click and simple navigation are implemented.

### CODE REVIEW

**Comment by esesyn01** [comment]
@bartoszLesniewski Could you please add here a short manual which tools are needed to build the app and run it on my phone with Android in order to test it?

**Comment by punfil** [comment]
> 

For now you need to install Android Studio (~3GB) + connect it to debugger and you're all set up.

**Comment by punfil** [comment]
> @bartoszLesniewski Could you please add here a short manual which tools are needed to build the app and run it on my phone with Android in order to test it?

For now you need to install Android Studio (~3GB) + connect the phone to debugger and you're all set up. We didn't test the app on the hardware, but on emulator.
https://developer.android.com/codelabs/build-your-first-android-app?fbclid=IwAR0EC2qLhYR7PzBzFMZMmKVoz0Z-3GFz6haLD3T0nHCE91tx_hwxpLFORqY#0

**Review by punfil — COMMENTED** [review]
Thank you very much for this template of the project. I managed to achieve the same. However, I have problems with building with your scripts as we use different OS for development. Please consider to clone only app folder (where all XML + source files are located)

**Comment by bartoszLesniewski** [comment]
> Thank you very much for this template of the project. I managed to achieve the same. However, I have problems with building with your scripts as we use different OS for development. Please consider to clone only app folder (where all XML + source files are located)

I've updated `.gitignore` and included only the directory with source files. Please check it now.

**Review by punfil — APPROVED** [review]
Well done! Just please merge into one commit.

**Review by esesyn01 — APPROVED** [review]
Looks good to me

**Pull request merged**
